name: Build

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
  test:

    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Executing lint test
        run: npm run lint

      - name: Build
        run: |
          npm run build
          rm -rf node_modules

      - name: Get latest commit hash
        run: |
          echo "MASTER_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{ github.repository }}/commit/$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Push frontend
        id: push_directory_frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: dist
          destination-github-username: 'Elitexv'
          destination-repository-name: 'Ulisha-store'
          user-name: github-actions[bot]
          user-email: github-actions[bot]@users.noreply.github.com
          commit-message: "Build from ${{ env.COMMIT_URL }}"
          target-branch: production